version: "3.2"

services:

  traefik:
    image: "traefik"
    extra_hosts:
      - media.${BASE_DOMAIN}:192.168.7.10
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    #removeme or #changeme 
    # there are some feautes that you can only do via traefik toml configs. 
    command: 
      - "--providers.file=true"
      - "--providers.file.filename=/etc/traefik/servers.toml"
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml:ro"
      - "./servers.toml:/etc/traefik/servers.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ${DATA_DIR}/traefik/acme.json:/etc/traefik/acme/acme.json
      - ${DATA_DIR}/traefik/htpasswd/:/htpasswd
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN}
    networks:
      - traefik
    restart: always

networks:
  traefik:
    external: true
